server:
  port: 8082

spring:
  application:
    name: book-service
  datasource:
    url: jdbc:h2:mem:bookdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 4
          min-idle: 0
  cache:
    type: redis
    redis:
      time-to-live: 60000
      use-key-prefix: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
